"""empty message

Revision ID: 013abd1c992d
Revises: 5859e9093f0d
Create Date: 2018-05-14 22:14:05.686843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013abd1c992d'
down_revision = '5859e9093f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_token')
    # ### end Alembic commands ###
