"""empty message

Revision ID: 04aff81bcbbf
Revises: fa01f7ca83d5
Create Date: 2018-04-11 10:25:47.368000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04aff81bcbbf'
down_revision = 'fa01f7ca83d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('reviews', sa.Column('date_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'date_modified')
    op.drop_column('reviews', 'date_created')
    # ### end Alembic commands ###
