"""empty message

Revision ID: 487f8a2aaa80
Revises: 8b20ea33c2ec
Create Date: 2018-05-19 23:21:56.638274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487f8a2aaa80'
down_revision = '8b20ea33c2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blacklist_token_key', 'blacklist', type_='unique')
    op.drop_column('reviews', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('blacklist_token_key', 'blacklist', ['token'])
    # ### end Alembic commands ###
